---
language: python
python:
  - '2.7'
sudo: required
services:
  - docker
env:
  global:
    - md_ignore: R1
    - secure: NVWn9ha/rJWIhX9Xadrsv1rJAvlFW+iUp/1vovv7+3XIn2NwRdhYkWX8mSw5NXuEHlEPVh4AZcNUIQPqLObnLrpz8aiR3Gq6dVrFD1HuhhQAOb+cS0cOSk4jEIxMHdq3OnkeZzCU9fONgA0NwOPQEbHOho92Y8wi9WDptfuA0HKi1f3kVJWdlERF9la8p5PkFWrqbdgbUc5SnCXgRjDysatVuu4fuN+a/z+GZU4Wi2dvbMfKoOTesmKoMx3ne1/LwN2Xq9ZdmmJfXmuxgV5ln7QOfFxSnKsaXPC6nxDvqm2T9nVz9cumTQum+c7Y4Q6yb9Ouojl/WmowA+NkBra3qu+adGU2hkB5sVeK6WOBYEm4epu9rHzTYZeq2PVPm/4lAB+4wODreE5G9g0X7TH6E4xyVafBP6VTyutAqqjN4k1BPRbQAlrA7TBPtIaBFEpDvSecssC13aV5gpHfwVtzXwh3mkuISINLawLEKffZd/W/nb8lAxjL4Nx956AN+n9OafsHyBWIwRnkdWIt0Yjl9bLWmwlYxicvLTOCEJulu6LPV+NylQSSDHIkLO8T6AWQf1/8dpY/2/TWqiQ9+qRxmmF+yf3hhRbWfJNMsIuWoISqYtPU0XKU2KPWCvQvbV23wJDGfaqBTMNVQZA8NHbiYgSr8U+K0deYojY+L+Rucbk=
  matrix:
    - SCENARIO='default'
before_install:
install:
  - pip install -r requirements.txt
before_script:
  - for file in `find . -maxdepth 2 -name "*.md"` ;  do markdownlint --ignore $md_ignore $file ; done
script:
  - molecule lint -s $SCENARIO
  - molecule dependency -s $SCENARIO
  - molecule syntax -s $SCENARIO
  - molecule create -s $SCENARIO
  - molecule converge -s $SCENARIO
  - molecule verify -s $SCENARIO
  - cd $TRAVIS_BUILD_DIR
after_success:
  - docker commit ui-centos7 quay.io/egi/ui:centos7
  - docker commit ui-centos6 quay.io/egi/ui:centos6
  - docker login -u="egi+packerbot" -p="$QUAY_PASSWORD" quay.io
  - docker push quay.io/egi/ui:centos6
  - docker push quay.io/egi/ui:centos7
after_failure:
before_deploy:
deploy:
after_deploy:
after_script:
  - molecule destroy
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
