---
language: python
python:
  - '2.7'
sudo: required
services:
  - docker
env:
  global:
    - md_ignore: R1
    - secure: LcBq5R5DcX7Vtdiqw3VRRHNpkf0+iuQxa2Rg1HaFI+5n3A3fAXOPezoONRNqTLUDRoVpQ6DwesVaSm2TgzytopqDzmXDg06ccuY/op9vXYau791/XGkGPH6gZR46Cv4paqYE6y/XgYcPjIC2J+gAOzjpjON7KC1Gnaf+mYYhgeh+RYxhoQBO5fTczJSgVPzRL5YPrPCr5lZ6UJp+agoSVAKfZjSMRESiWIA4iaC7GPDvnR6eK2kR1sXzuOR0gBQMyBO0Ole3SRWw+QpDnvHl/g8uIF8J+kHXxxSVYS4EXWstaN7+lDd7dF+stwjHsfLc7UTAoiGpcsJhiqKQ3UBeVbkaicpEnyYDNeTOfgI0UbYT8D/DSZ0fVpPA0mTadA3J0YGsPOpdf8UNBEOUGxmTqG7EPou7dkFI7eVEdLiyQ/Tuz45oSJp3HqGFtiFWiMJEJzXIBXEKcViFEio1F9Slemwg8Yp75IBefs9YIV/+0tHXrIVPULuSxpaflSVIkol/wdmQlkie1we7IeYBUfjB86YJGsF/kiRi5meoiJI8IpHWAkTKGPvFWgqiVmGeyZHueyxKi73IeqBrgS3VvUgi0Xbq2QlsDgjk+zASTJ7KUtHaOHr0yuTbvElbb/wsv5ojSpDvUEp3smrrsVcCa1RyE1CqsBvVbYiZlv1d5dqXsV8=
  matrix:
    - SCENARIO='default'
before_install:
install:
  - pip install -r requirements.txt
before_script:
  - for file in `find . -maxdepth 2 -name "*.md"` ;  do markdownlint --ignore $md_ignore $file ; done
script:
  - molecule lint -s $SCENARIO
  - molecule dependency -s $SCENARIO
  - molecule syntax -s $SCENARIO
  - molecule create -s $SCENARIO
  - molecule converge -s $SCENARIO
  - molecule verify -s $SCENARIO
  - cd $TRAVIS_BUILD_DIR
after_success:
  - docker commit ui-centos7 quay.io/egi/ui:centos7
  - docker commit ui-centos6 quay.io/egi/ui:centos6
  - docker login -u="egi+packerbot" -p="$QUAY_PASSWORD" quay.io
  - docker push quay.io/egi/ui:centos6
  - docker push quay.io/egi/ui:centos7
after_failure:
before_deploy:
deploy:
after_deploy:
after_script:
  - molecule destroy
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
