---
language: python
python:
  - '2.7'
sudo: required
services:
  - docker
env:
  global:
    - md_ignore: R1
    - secure: CqXJOwIKK61rVmS3iYi6S6e6JlgrmUXi5ZXtUtOwf2sCyr6oUuoq1MjyM1SQHgXuaIxsDKYkKayePqJx74pCOEZEF0s3xjKN5bVSgQ9vLVjqJY/zzbJYJOwPc2n+z8P7pPDmnkeGbLL2krvU7Sd8BvWXe1L7nfgUfMoVt1g6Fu+PLZA8Otzen/DRfR3bgIAjATwA5LlOucvpjYwdQ0RhMmSwzvS7Lb3bPNyM0FzFZpPLx3qouqsxyUD/ZCGVFkJ7FPvYmVAZLVrwgHPclQ8kYw4vFM5F5G+cMVQFZ3V7vPuLj68LIsdygE6yCysMDpvQzOMMaMPYLmNw9PCH5eIlaFW2mkw45Wh7BMmSkrXMmi3FZ9DFRD/ATR7g7Bu4v4/Q1pmc303MOA292gKlcK+o2WivRIsR4XYjS4wdbuNApd9B00OAaqqwhcAZq5L2l0BPiSYv4dTsn60VinudMDqMSDRnRAGZ3mVUtONuFo26dNuyHiPRzPNvRfYdfSzjlc9wtUxlXRZhygITpBmR7Dc9oAaduoRsAzBnJUZua8ygrxLeSQaSSvQ2/bNBFIj9sG4hrYCDSulpi5XpqmT2srsSGJ+WxC3mJPiToaPtwjCAxYBFTwymDl7JPk9xlXCPxLHxFnAVV3rRZKTejb6MJeyFumZjKStOpjPa0vteukyvgZs=
  matrix:
    - SCENARIO='default'
before_install:
install:
  - pip install -r requirements.txt
before_script:
  - 'for file in `find . -maxdepth 2 -name "*.md"` ;  do markdownlint --ignore $md_ignore
  $file ; done'
script:
  - molecule lint -s $SCENARIO
  - molecule dependency -s $SCENARIO
  - molecule syntax -s $SCENARIO
  - molecule create -s $SCENARIO
  - molecule converge -s $SCENARIO
  - molecule verify -s $SCENARIO
  - cd $TRAVIS_BUILD_DIR
after_success:
  - docker commit ui-centos7 quay.io/egi/ui:centos7
  - docker commit ui-centos6 quay.io/egi/ui:centos6
  - docker login -u="egi+packerbot" -p="$QUAY_PASSWORD" quay.io
  - docker push quay.io/egi/ui:centos6
  - docker push quay.io/egi/ui:centos7
after_failure:
before_deploy:
deploy:
after_deploy:
after_script:
  - molecule destroy
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
