---
# tasks file for ansible-ui
- name: Install metapackage
  package:
    name: "{{ item }}"
    state: present
  loop: "{{prerequisites[ansible_os_family | lower][ansible_distribution_major_version]}}"

- name: Ensure extra packages as per spec
  package:
    name: "{{ item }}"
    state: present
  loop: "{{missed_dependencies[ansible_os_family |lower][ansible_distribution_major_version] }}"

- name: Ensure optional packages if option is selected
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ optional_packages[ansible_os_family |lower][ansible_distribution_major_version] }}"
  when: install_optional_packages

- name: Ensure weak ciphers are not included by default
  replace:
    path: /etc/ssh/ssh_config
    regexp: '^\#?\s+Ciphers.*$'
    replace: Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
    validate: ssh -f %s -V

- name: Ensure groups
  group:
    name: "{{ item.name }}"
    state: present
    gid: "{{ item.gid }}"
    system: false
  loop: "{{configured_groups}}"

- name: Add local users
  user:
    name: "{{ item.0['name'] }}"
    create_home: true
    ssh_key_bits: 2048
    groups: "{{ item.1['name'] }}"
    group: "{{ item.0['default_group'] }}"
    state: present
    system: false
    ssh_key_type: rsa
    ssh_key_comment: ansible-generated
    ssh_key_file: .ssh/id_rsa
    update_password: always
    shell: "{{ item.0['shell'] }}"
  loop: "{{ configured_users | zip(configured_groups)| list}}"

