---
# tasks file for ansible-ui
- name: Install metapackage
  package:
    name: "{{ item }}"
    state: present
  loop: "{{prerequisites[ansible_os_family | lower][ansible_distribution_major_version]}}"

- name: Ensure groups
  group:
      name: "{{ item.name }}"
      state: present
      gid: "{{ item.gid }}"
      system: no
  loop: "{{configured_groups}}"

- name: Add local users
  user:
      name: "{{ item.0['name'] }}" # required. Name of the user to create, remove or modify.
      create_home: yes
      ssh_key_bits: 2048
      groups: "{{ item.1['name'] }}"
      group: "{{ item.0['default_group'] }}"
      state: present
      system: no
      ssh_key_type: rsa
      ssh_key_comment: ansible-generated
      ssh_key_file: .ssh/id_rsa
      update_password: always # not required. choices: always;on_create. C(always) will update passwords if they differ.  C(on_create) will only set the password for newly created users.
      shell: "{{ item.0['shell'] }}"
  loop: "{{ configured_users | zip(configured_groups)| list}}"