---
- name: CVE-2018-12020 | gnupg2
  package:
    name: gnupg2-2.0.22-5.el7_5
    state: present
    update_cache: true

- name: RHSA-2018:2123 | python
  package:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - python-2.7.5-69.el7_5
    - python-libs-2.7.5-69.el7_5

- name: RHSA-2018:2285 | yum
  package:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - yum-plugin-ovl-1.1.31-46.el7_5
    - yum-utils-1.1.31-46.el7_5
    - yum-plugin-priorities-1.1.31-46.el7_5
    - yum-plugin-fastestmirror-1.1.31-46.el7_5

- name: RHSA-2018:2943 | openjdk
  package:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - java-1.8.0-openjdk-headless-1.8.0.191.b12-0.el7_5
    - java-1.8.0-openjdk-1.8.0.191.b12-0.el7_5

- name: RHSA-2018:2898 | nss
  package:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - nss-sysinit-3.36.0-7.el7_5
    - nss-3.36.0-7.el7_5
    - nss-tools-3.36.0-7.el7_5
