---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ui-centos7
    image: quay.io/egi/voms-client:centos7
  - name: ui-centos6
    image: quay.io/egi/voms-client:centos6
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  # Parallel testing only possible with xdist
  options:
    n: 2
  lint:
    name: flake8
